services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth_app_container
    ports:
      - '3010:3010'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - auth
    restart: unless-stopped # ← retry if it crashes on boot

  postgres:
    image: postgres:16
    container_name: pg_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auth
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - auth
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d auth']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    networks:
      - auth
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    networks:
      - auth
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_container
    ports:
      - '5540:5540'
    networks:
      - auth
    depends_on:
      redis:
        condition: service_healthy

networks:
  auth:
    driver: bridge

volumes:
  pg_data:
