# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auth
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - auth

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    networks:
      - auth
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    networks:
      - auth

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_container
    ports:
      - '5540:5540'
    networks:
      - auth
    depends_on:
      - redis

networks:
  auth:
    driver: bridge

volumes:
  pg_data:
