server {
    listen 80;

    server_name your-domain.com;
    # Which domain/IP this block applies to.
    # For dev, just put your EC2 public IP here e.g: 54.123.45.67

    location / {
        # For ALL incoming requests (the "/" means catch-everything)...

        proxy_pass http://127.0.0.1:3000;
        # ...forward them to your NestJS app running on port 3000.
        # "localhost" = same EC2 machine. Nginx and NestJS are on same server.

        proxy_http_version 1.1;
        # Use HTTP/1.1 (required for WebSocket support and keep-alive connections)

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        # These two handle WebSocket upgrades (e.g. Socket.io).
        # If you don't use WebSockets, they're harmless to keep.

        proxy_set_header Host $host;
        # Pass the original Host header to NestJS.
        # Without this, NestJS sees "localhost" instead of your actual domain.

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
        # Pass the REAL user IP to NestJS.
        # Without this, req.ip in NestJS would always show 127.0.0.1 (Nginx's IP)
        # instead of the actual client's IP.
        # The X-Forwarded-Proto header tells NestJS whether the original request was HTTP or HTTPS.
        

        proxy_cache_bypass $http_upgrade;
        # Don't serve cached responses for WebSocket upgrade requests.
    }

    location /health {
        proxy_pass http://127.0.0.1:3000/health;s
        access_log off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
}